name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pyttsx3
        pip install playsound
        pip install mysql-connector-python
        pip install flake8 pytest
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
    - name: Lint with flake8
        run: |         
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics        
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics   
